### ISSUE TITLE
PeriodicTask not working if i exit from app. why?

### ISSUE THREAD

**Issue by ananth10** [googlesamples/android-gcmnetworkmanager#3]

**Comment by samtstern** [comment]
@ananth10 can you provide more details as to exactly what is not working?

**Comment by ananth10** [comment]
@samtstern . i am just using this sample app. but when i start periodic task i can see the toast message after every 5 sec. but if i exit from app i could not see that toast message. is it working like android service or different.
![device-2016-03-02-105512](https://cloud.githubusercontent.com/assets/13381242/13451486/72cbe342-e065-11e5-940b-8afec634cc10.png)
![device-2016-03-02-105620](https://cloud.githubusercontent.com/assets/13381242/13451489/77cf5496-e065-11e5-8348-cf7136303cb6.png)

**Comment by samtstern** [comment]
This is working as intended, although it may be a little confusing.  When the task is completed in the service it sends a broadcast down to the Activity, which is responsible for displaying the Toast.  However the Activity is only listening for these broadcasts when it is in the foreground, which is why you're not seeing the Toast once the app is closed.
